name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"   # run every 15 minutes

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Fallback essentials (in case requirements.txt is minimal)
          pip install requests pandas numpy ta || true

      - name: Generate mapping & run analyses
        run: |
          set -e
          mkdir -p data reports
          # Create mapping CSV/JSON
          python scripts/mapping.py --out data/revolut_mapping.json --csv data/revolut_mapping.csv
          # Produce analysis summary
          python scripts/analyses.py --mapping data/revolut_mapping.json --out reports/summary.md

      - name: Publish run summary
        if: always()
        run: |
          echo "## Revolut mapping & market scan" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f reports/summary.md ]; then
            cat reports/summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "_No summary produced._" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Changed files" >> $GITHUB_STEP_SUMMARY
          git status --porcelain >> $GITHUB_STEP_SUMMARY || true

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update mapping & analysis [skip ci]"
            git push
          fi