name: Run mapping & analyses

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Run analyses
        run: |
          python -m scripts.analyses

      - name: Prepare outputs
        run: |
          mkdir -p public_runs/latest
          cp artifacts/*.json public_runs/latest/ || true
          cp data/*.json public_runs/latest/ || true

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public_runs/latest/*.json
          git commit -m "update summary [skip ci]" || echo "No changes"
          git push

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public_runs