name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Revolut mapping
        run: python scripts/mapping.py

      - name: Commit mapping artifacts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/revolut_mapping.csv data/revolut_mapping.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update Revolut mapping [skip ci]"
            git push
          else
            echo "No mapping changes."
          fi

      - name: Run A+ Setup Scan (open-source data)
        run: |
          set -e
          python scripts/analysis.py
        env:
          EQUITY_USD: "41338.00"
          CASH_USD: "32000.00"
          FLOOR_USD: "36500"
          FLOOR_BUFFER: "1000"
          DAILY_PNL_PCT: "0.0"

      - name: Show decision
        run: |
          echo "----- DECISION -----"
          if [ -f data/signals.json ]; then
            python - <<'PY'
import json
j=json.load(open("data/signals.json"))
t=j.get("type")
if t=="C":
    print("Hold and wait.")
elif t=="A":
    print("Raise cash now.")
else:
    for line in j.get("text_lines", []):
        print(line)
PY
          else
            echo "No signals.json produced."
          fi
          echo "--------------------"

      - name: Save analysis artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analysis-output
          path: |
            data/market_snapshot.json
            data/signals.json

      - name: Commit analysis outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/market_snapshot.json data/signals.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: analysis outputs"
            git push
          else
            echo "No analysis changes."
          fi