name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    # Run every 15 minutes; router below decides deep vs light-hourly.
    - cron: "*/15 * * * *"

permissions:
  contents: write       # to commit public_runs
  pages: write          # to deploy to GitHub Pages
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure output tree
        run: |
          mkdir -p public_runs/latest
          echo "Tree OK"

      - name: Generate Revolut ↔ Binance mapping
        run: |
          set -e
          echo "[mapping] generating…"
          python scripts/mapping.py
          echo "[mapping] generated data/revolut_mapping.csv and data/revolut_mapping.json"

      # ---- Router: choose deep vs light-hourly (no light-fast) ----
      - name: Decide run mode (deep / light-hourly)
        id: router
        shell: bash
        run: |
          set -euo pipefail
          MIN=$(date -u +%M)
          MODE="light-hourly"
          # Pick one minute per hour for deep runs; adjust as you like.
          if [ "$MIN" = "49" ]; then MODE="deep"; fi
          echo "Selected mode: $MODE (UTC minute=${MIN})"
          echo "mode=$MODE" >> "$GITHUB_OUTPUT"

      - name: Run analyses (deep)
        if: steps.router.outputs.mode == 'deep'
        run: |
          echo "[router] Running DEEP analyses"
          python scripts/analyses.py --mode deep

      - name: Run analyses (light-hourly at :02)
        if: steps.router.outputs.mode == 'light-hourly'
        run: |
          echo "[router] Running LIGHT-HOURLY analyses"
          python scripts/analyses.py --mode light-hourly

      - name: Commit public_runs to main
        run: |
          set -e
          if [ -n "$(git status --porcelain public_runs || true)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public_runs
            git commit -m "Update public_runs: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          else
            echo "No changes to commit."
          fi

      # ---- GitHub Pages ----
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to gh-pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Verify Pages endpoint (non-blocking)
        if: always()
        env:
          CHECK_URL: ${{ steps.deploy.outputs.page_url }}
        run: |
          URL="${CHECK_URL:-$PAGES_URL}"
          echo "Checking ${URL}"
          curl -sSL -o /dev/null -w "HTTP/%{http_version} %{http_code}\n" "${URL}" || true