name: Run mapping & analyses

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # run every 30 minutes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EQUITY: "41000"   # default fallback
      CASH: "32000"     # default fallback

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas requests ta
          fi

      - name: Generate mapping & run analyses
        run: |
          set -e
          python scripts/mapping.py
          echo "✅ Generated data/revolut_mapping.csv and data/revolut_mapping.json"
          export PYTHONPATH="$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/scripts"
          python -m scripts.analyses

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: market-output
          path: |
            artifacts/**
            data/market_snapshot.json
            data/signals.json

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data artifacts
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update data & snapshot [skip ci]"
            git push
          fi