name: Build Revolut Mapping

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # daily every 15 mins

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate mapping
        run: |
          python scripts/map_revolut_coins.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/revolut_mapping.csv data/revolut_mapping.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update Revolut mapping [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
