name: Run mapping & analyses

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Generate mapping (safe)
        run: |
          if [ -f scripts/mapping.py ]; then
            python scripts/mapping.py
          else
            echo "No mapping.py found; skipping mapping generation."
          fi

      - name: Run analyses
        run: python -m scripts.analyses

      - name: Publish artifacts into public_runs
        run: |
          mkdir -p public_runs/latest
          ts="$(date -u +'%Y-%m-%dT%H-%M-%SZ')"
          mkdir -p "public_runs/$ts"

          if [ -f artifacts/market_snapshot.json ]; then cp artifacts/market_snapshot.json public_runs/latest/market_snapshot.json; fi
          if [ -f data/signals.json ]; then cp data/signals.json public_runs/latest/signals.json; fi
          if [ -f artifacts/run_stats.json ]; then cp artifacts/run_stats.json public_runs/latest/run_stats.json; fi
          if [ -f artifacts/debug_scan.json ]; then cp artifacts/debug_scan.json public_runs/latest/debug_scan.json; fi

          cp -r public_runs/latest/* "public_runs/$ts/" || true

      - name: Build summary.json
        run: python scripts/build_summary.py

      - name: Verify summary.json
        run: |
          set -e
          test -f public_runs/latest/summary.json
          sz=$(wc -c < public_runs/latest/summary.json || echo 0)
          echo "summary.json size: $sz bytes"
          [ "$sz" -ge 50 ]

      - name: Commit changes to main (rebase-safe)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git -c rebase.autoStash=true pull --rebase origin main || true
          git add -A data artifacts public_runs || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: update analyses outputs [skip ci]" || true
            git push origin HEAD:main
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public_runs
          force_orphan: true