name: Build mapping & analyses

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

concurrency:
  group: build-mapping-analyses
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests rapidfuzz pandas numpy python-dateutil

      - name: Ensure output tree
        run: |
          rm -rf public_runs
          mkdir -p public_runs/latest

      - name: Generate Revolut↔Binance mapping
        run: |
          set -e
          python scripts/generate_mapping.py

      - name: Run analyses
        env:
          RUN_OUT_DIR: public_runs/latest
        run: |
          set -e
          python -m scripts.analyses

      - name: Commit public_runs to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A public_runs mapping
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update public_runs and mapping [skip ci]"
            git push
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public_runs
          force_orphan: true