name: Run mapping & analyses

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EQUITY: ${{ vars.EQUITY }}
      CASH: ${{ vars.CASH }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate mapping & run analyses
        run: |
          set -e
          python scripts/mapping.py
          echo "✅ Generated data/revolut_mapping.csv and data/revolut_mapping.json"
          export PYTHONPATH="$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/scripts"
          python -m scripts.analyses

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: market-output
          path: |
            artifacts/**
            data/market_snapshot.json
            data/signals.json

      - name: Commit changes
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data artifacts
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update data & snapshot [skip ci]"
            git push
          fi