name: build

on:
  push:
    paths:
      - 'scripts/**'
      - 'data/**'
      - '.github/workflows/build.yml'
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dateutil ta

      - name: Generate mapping & run analyses
        run: |
          set -e
          python scripts/mapping.py
          echo "✅ Generated data/revolut_mapping.csv and data/revolut_mapping.json"
          export PYTHONPATH="$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/scripts"
          python -m scripts.analyses

      # Shows the latest JSON snapshot directly in the Actions summary tab
      - name: Publish run summary
        if: always()
        run: |
          echo "### Market snapshot" >> $GITHUB_STEP_SUMMARY
          if [ -f data/market_snapshot.json ]; then
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat data/market_snapshot.json >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "_No snapshot produced._" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload market snapshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: market_snapshot
          path: |
            data/market_snapshot.json
            data/revolut_mapping.csv
            data/revolut_mapping.json
          if-no-files-found: ignore

      - name: Commit changes
        if: success() || failure()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update mapping and snapshot [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi