name: Run mapping & analyses

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      # Optional: only runs if scripts/mapping.py exists
      - name: Generate mapping (safe)
        run: |
          set -e
          if [ -f scripts/mapping.py ]; then
            python scripts/mapping.py
          else
            echo "No scripts/mapping.py found; skipping."
          fi

      - name: Run analyses
        env:
          EQUITY: ${{ vars.EQUITY || '41000' }}
          CASH:   ${{ vars.CASH   || '32000' }}
        run: |
          set -e
          python -m scripts.analyses

      - name: Verify outputs exist
        run: |
          set -e
          test -f public_runs/latest/summary.json
          echo "summary.json present."

      - name: Commit changes to main (conflict-safe)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "=== Status before staging ==="
          git status --porcelain

          git add -A data artifacts public_runs

          echo "=== Status after staging ==="
          git status --porcelain

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git fetch origin main
            git pull --rebase --autostash origin main || true
            git commit -m "ci: update analyses outputs [skip ci]"
            git push origin HEAD:main
          fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public_runs
          force_orphan: true

      # GitHub Pages propagation can lag; retry until it’s live
      - name: Verify Pages endpoint
        run: |
          set -e
          url="https://armendq.github.io/revolut_crypto_mapping/latest/summary.json"
          echo "Checking $url"
          for i in {1..10}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            echo "Attempt $i: HTTP $code"
            if [ "$code" = "200" ]; then
              echo "✅ Pages is serving summary.json"
              exit 0
            fi
            sleep 20
          done
          echo "❌ Failed to verify $url after retries"
          exit 1
```0