name: exec-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  trade:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests python-binance

      - name: Run bot
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          DRY_RUN: "0"                # set 0 for live trading
          FORCE_EQUITY_USD: "30"      # pretend only 30 USDC available
          QUOTE_ASSET: "USDC"         # only act on …USDC pairs
        run: python exec_bot.py
