name: exec-bot

on:
  workflow_dispatch:        # allow manual run
  schedule:
    - cron: "*/5 * * * *"   # run every 5 minutes

jobs:
  trade:
    runs-on: [self-hosted]   # your Hetzner runner

    permissions:
      contents: write        # allow committing state file

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests python-binance

      - name: Run bot
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          DRY_RUN: "1"                # set "0" for live trading
          FORCE_EQUITY_USD: "0"      # simulate 30 USDC balance
          QUOTE_ASSET: "USDC"         # scan/trade only ...USDC pairs
        run: python exec_bot.py

      - name: Persist state
        run: |
          if [ -f state/open_positions.json ]; then
            git config user.name "bincrypare-bot"
            git config user.email "bot@users.noreply.github.com"
            git add state/open_positions.json
            git diff --cached --quiet || git commit -m "state: update open positions"
            git push || true
          fi
