name: exec-bot

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: exec-bot
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"

jobs:
  trade:
    runs-on: [self-hosted]   # your Hetzner runner
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-binance

      - name: Run bot
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          DRY_RUN: "0"                 # 1=dry run, 0=live
          FORCE_EQUITY_USD: "0"        # use real USDC balance
          QUOTE_ASSET: "USDC"          # act only on ...USDC pairs
          TRADE_CANDIDATES: "0"        # set "1" to trade C signals too
        run: python exec_bot.py

      - name: Persist state
        run: |
          git config --global safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "bincrypare-bot"
          git config user.email "bot@users.noreply.github.com"
          if [ -f state/open_positions.json ]; then
            git add state/open_positions.json
            git diff --cached --quiet || git commit -m "state: update open positions"
            git fetch origin main
            git pull --rebase origin main || true
            git push origin HEAD:main || true
          else
            echo "No state file to persist."
          fi