name: scan-and-exec

on:
  schedule:
    - cron: "*/7 * * * *"    # every 7 minutes (reduced overlap)
  workflow_dispatch:
    inputs:
      ignore_regime:
        description: "Set 1 to bypass BTC regime"
        required: false
        default: "1"         # default ON for manual runs

permissions:
  contents: write

concurrency:
  group: scan-and-exec-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHONUNBUFFERED: "1"
  BINANCE_BASE_URL: https://data-api.binance.vision

  # ---- loosened thresholds to produce signals in quiet tape ----
  IGNORE_REGIME: "1"        # <— force regime bypass for scheduled runs
  RELAX_B_HIGH: "0"         # use 1h close to confirm (more permissive than high)
  BREAK_BUFFER_ATR: "0.02"  # smaller buffer above HH20
  VOL_Z_MIN_BREAK: "0.9"    # was 1.3/1.2
  VOL_Z_MIN_PRE: "0.7"      # was 1.0
  PROX_ATR_MIN: "0.00"
  PROX_ATR_MAX: "0.70"      # wider pre-breakout window
  MIN_AVG_VOL: "2500"       # accept lower liquidity for discovery (still filtered)
  STOP_ATR_BUFFER: "0.4"    # used by analyses sizing logic
  MIN_RISK_FLOOR_PCT: "0.008"
  MAX_RISK_CAP_PCT: "0.05"
  MAX_WORKERS: "12"
  LOG_LEVEL: "INFO"

jobs:
  run:
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-binance numpy

      - name: Ensure output dirs
        run: mkdir -p public_runs/latest state

      # ---------- ANALYSES ----------
      - name: Run analyses (deep, USDC)
        run: |
          set -euo pipefail
          # allow manual override via dispatch input
          IGN_INPUT="${{ github.event.inputs.ignore_regime || '' }}"
          IGN="${IGNORE_REGIME}"
          if [ -n "${IGN_INPUT}" ]; then IGN="${IGN_INPUT}"; fi
          ARGS="--mode deep"
          if [ "${IGN}" = "1" ]; then ARGS="$ARGS --ignore_regime"; fi

          echo "Running analyses with ARGS: $ARGS"
          python -m scripts.analyses $ARGS
          test -s public_runs/latest/summary.json

          python - <<'PY'
          import json
          p=json.load(open('public_runs/latest/summary.json'))
          uni=p.get("universe",{})
          print("signals:", p.get("signals"),
                "| regime:", p.get("regime"),
                "| scanned:", uni.get("scanned"),
                "| eligible:", uni.get("eligible"),
                "| cands:", len(p.get("candidates",[])),
                "| orders:", len(p.get("orders",[])))
          if p.get("signals",{}).get("type")=="HOLD":
              # dump top 5 candidates by score (if any) to see why they missed B
              cs=sorted(p.get("candidates",[]), key=lambda x:x.get("score",0), reverse=True)[:5]
              for i,c in enumerate(cs,1):
                  print(f"[TOP{ i }] {c['symbol']} score={c.get('score')} vz={c.get('vol_z')} prox={c.get('prox_atr')} notes={c.get('notes')}")
          PY

      # ---------- EXECUTE BEFORE ANY GIT OPS ----------
      - name: Run exec bot on fresh local summary
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          DRY_RUN: "0"                 # live
          FORCE_EQUITY_USD: "0"        # use live USDC balance
          QUOTE_ASSET: "USDC"
          TRADE_CANDIDATES: "1"        # place stop-limit for C
          C_RISK_MULT: "0.7"           # little more aggressive on C
          STOP_LIMIT_OFFSET: "0.002"   # +0.2% above entry
          SUMMARY_URL: "file://${{ github.workspace }}/public_runs/latest/summary.json"
        run: |
          set -euo pipefail
          if grep -qE '^(<<<<<<<|=======|>>>>>>>)' public_runs/latest/summary.json; then
            echo "ERROR: summary.json has merge markers. Aborting exec."
            sed -n '1,120p' public_runs/latest/summary.json || true
            exit 1
          fi
          python exec_bot.py

      # ---------- COMMIT SCAN ARTIFACTS ----------
      - name: Commit public_runs
        run: |
          set -euo pipefail
          git config --global safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "bincrypare-bot"
          git config user.email "bot@users.noreply.github.com"
          git config --global pull.rebase false

          git add public_runs
          if git diff --cached --quiet; then
            echo "No public_runs changes."
          else
            git commit -m "scan: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          fi

          git fetch origin main || true
          git merge -X ours --no-edit origin/main || true
          if [ -e .git/MERGE_HEAD ]; then
            git checkout --ours public_runs/latest/summary.json || true
            git add public_runs/latest/summary.json || true
            git commit -m "merge(resolved with -X ours for summary): $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
          fi
          git push origin HEAD:main || true

      # ---------- COMMIT STATE ONLY ----------
      - name: Persist state
        run: |
          set -euo pipefail
          git config --global safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "bincrypare-bot"
          git config user.email "bot@users.noreply.github.com"
          git config --global pull.rebase false

          if [ -f state/open_positions.json ]; then
            if grep -qE '^(<<<<<<<|=======|>>>>>>>)' state/open_positions.json; then
              echo "Conflict in state file; using ours."
              git checkout --ours state/open_positions.json || true
            fi

            git add state/open_positions.json
            if git diff --cached --quiet; then
              echo "No state changes."
            else
              git commit -m "state: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            fi

            git fetch origin main || true
            git merge -X ours --no-edit origin/main || true
            if [ -e .git/MERGE_HEAD ]; then
              git checkout --ours state/open_positions.json || true
              git add state/open_positions.json || true
              git commit -m "merge(state resolved with -X ours): $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
            fi
            git push origin HEAD:main || true
          else
            echo "No state file to persist."
          fi