name: scan-and-exec

on:
  schedule:
    - cron: "*/7 * * * *"   # every 7 minutes, avoids overlap
  workflow_dispatch:
    inputs:
      ignore_regime:
        description: "Set 1 to bypass BTC regime"
        required: false
        default: "0"

permissions:
  contents: write

concurrency:
  group: scan-and-exec-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHONUNBUFFERED: "1"
  BINANCE_BASE_URL: https://data-api.binance.vision
  # Relaxed thresholds for more signals
  RELAX_B_HIGH: "0"          # confirm with close, not high
  BREAK_BUFFER_ATR: "0.03"
  VOL_Z_MIN_BREAK: "1.2"
  VOL_Z_MIN_PRE: "1.0"
  PROX_ATR_MIN: "0.02"
  PROX_ATR_MAX: "0.50"
  MIN_AVG_VOL: "4000"
  STOP_ATR_BUFFER: "0.4"
  MIN_RISK_FLOOR_PCT: "0.01"
  MAX_RISK_CAP_PCT: "0.04"
  MAX_WORKERS: "8"
  LOG_LEVEL: "INFO"

jobs:
  run:
    runs-on: [self-hosted]          # your Hetzner runner
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-binance numpy

      # ---------- ANALYSES ----------
      - name: Ensure output dirs
        run: mkdir -p public_runs/latest state

      - name: Run analyses (deep, USDC)
        run: |
          set -euo pipefail
          IGN="${{ github.event.inputs.ignore_regime || '0' }}"
          if [[ "$IGN" == "1" ]]; then
            python -m scripts.analyses --mode deep --ignore_regime
          else
            python -m scripts.analyses --mode deep
          fi
          test -s public_runs/latest/summary.json
          python -c "import json; p=json.load(open('public_runs/latest/summary.json')); print('signals:', p.get('signals'), 'regime:', p.get('regime'))"

      # ---------- COMMIT SCAN ARTIFACTS ----------
      - name: Commit public_runs
        run: |
          set -euo pipefail
          git config --global safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "bincrypare-bot"
          git config user.email "bot@users.noreply.github.com"

          git add public_runs
          if git diff --cached --quiet; then
            echo "No public_runs changes."
          else
            git commit -m "scan: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          fi

          git pull --rebase origin main || true
          git push origin HEAD:main || true

      # ---------- EXECUTOR ----------
      - name: Run exec bot on fresh local summary
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          DRY_RUN: "0"                 # 1=dry, 0=live
          FORCE_EQUITY_USD: "0"        # use live USDC
          QUOTE_ASSET: "USDC"
          TRADE_CANDIDATES: "1"        # trade C via stop-limit
          C_RISK_MULT: "0.5"           # candidates at half risk
          STOP_LIMIT_OFFSET: "0.001"   # +0.1% above entry
          SUMMARY_URL: "file://${{ github.workspace }}/public_runs/latest/summary.json"
        run: |
          set -euo pipefail
          python exec_bot.py

      # ---------- COMMIT STATE ONLY ----------
      - name: Persist state
        run: |
          set -euo pipefail
          git config --global safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "bincrypare-bot"
          git config user.email "bot@users.noreply.github.com"

          if [ -f state/open_positions.json ]; then
            git add state/open_positions.json
            if git diff --cached --quiet; then
              echo "No state changes."
            else
              git commit -m "state: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            fi
            git pull --rebase origin main || true
            git push origin HEAD:main || true
          else
            echo "No state file to persist."
          fi